DBC22-1096: Updated site logo to desired
bcgov/DriveBC.ca pull request #147
Opened 2023-10-24 19:59 UTC by bcgov-brwang

Updated site logo to desired

2023-10-24 22:34 UTC, ray-oxd requested changes
Please add styling to make site display consistent with the header section in Figma. https://www.figma.com/file/jPCiQba8B7t9VPXbnABoW2/DriveBaC-Website?type=design&node-id=2875-24092&mode=design

Also, remove unused image file.

2023-10-27 17:41 UTC, ray-oxd submitted a review, later dismissed

2023-10-27 17:41 UTC, minORC approved these changes

2023-10-27 17:42 UTC, minORC submitted a review, later dismissed

2023-10-27 17:48 UTC, ray-oxd commented
Replaced with a new branch.

2023-10-27 17:48 UTC, closed without merging