DBC22-2401: fixed the issue of map's moving when side panel open and …
bcgov/DriveBC.ca pull request #560
Opened 2024-07-25 15:20 UTC by bcgov-brwang

…close

DBC22-2401: fixed the issue of map's moving when side panel open and close
This PR created a function to adjust the map window for setting dynamic class for my location button and route search component. This fix changed map's position to absolute and push my location and route search component to the right to avoid the side panel covers these components.
Jira: https://jira.th.gov.bc.ca/browse/DBC22-2401

2024-08-02 20:16 UTC, ray-oxd commented
Desktop looks great now.
- Please resolve conflict. Consult @minORC if you're not sure which classes to keep
- Remove the commented RouteSearch_old if no longer needed
- Mobile panel "unfolds" from the top now, and expands after clicking on it. This doesn't feel intentional?

2024-08-02 20:18 UTC, ray-oxd requested changes
Desktop looks great now.
- Please resolve conflict. Consult @minORC if you're not sure which classes to keep
- Remove the commented RouteSearch_old if no longer needed
- Mobile panel "unfolds" from the top now, and expands after clicking on it. This doesn't feel intentional?
- Mobile search bar slides in from the right when though it is covered from the panel. Please disable this animation in mobile.

2024-08-02 20:31 UTC, fatbird submitted a review, later dismissed

2024-08-07 20:38 UTC, ray-oxd approved these changes

2024-08-07 20:43 UTC, merged