DBC22-2842: appended camIndex in the url when sharing camera's URL
bcgov/DriveBC.ca pull request #697
Opened 2024-10-29 16:45 UTC by bcgov-brwang

DBC22-2842: appended camIndex in the url when sharing camera's URL

2024-10-29 21:17 UTC, ray-oxd requested changes
functionality is good but please make it so that when we switch camera views, the browser's URL gets updated immediately with the camIndex included. We want users to be able to copy and paste from the window directly.

2024-10-29 21:37 UTC, bcgov-brwang commented
> functionality is good but please make it so that when we switch camera views, the browser's URL gets updated immediately with the camIndex included. We want users to be able to copy and paste from the window directly.

Updated: https://github.com/bcgov/DriveBC.ca/pull/700/commits/499c79b000a92c5a885cc4396348444764d7bae1

2024-11-02 01:37 UTC, ray-oxd commented on src/frontend/src/Components/map/panels/CamPanel.js
> +    window.history.replaceState({}, "", url);
Please use const [searchParams, setSearchParams] = useSearchParams(); in this file instead of manually setting and getting.

2024-11-02 01:38 UTC, ray-oxd commented on src/frontend/src/Components/shared/ShareURLButton.js
> +
Please undo changes here if they're not needed. If we've updated the URL at this point then this component doesn't need to change.

2024-11-06 00:59 UTC, ray-oxd approved these changes

2024-11-06 00:59 UTC, merged